const fs = require('fs');
const path = require('path');

const SHARED_CSS = fs.readFileSync(
  path.join(__dirname, '..', '..', 'templates', 'site', 'shared-style.css'),
  'utf8'
);

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function wasiHtml({ title, programName, language }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<link rel="stylesheet" href="style.css" />
</head>
<body>
<div class="wrap">
  <header>
    <span class="badge">${escapeHtml(language)} &rarr; WebAssembly</span>
    <h1>${escapeHtml(programName)}</h1>
    <p>Compiled from ${escapeHtml(language)} to a <code>wasm32-wasip1</code> module and run entirely in your browser via WebAssembly &mdash; no server involved.</p>
  </header>
  <div class="panel">
    <button id="run-btn">Run</button>
    <span id="status" class="badge" style="margin-left:.5rem;background:transparent;color:var(--muted)"></span>
  </div>
  <div class="panel">
    <div id="output" class="terminal"><span class="muted">Click "Run" to execute the compiled WebAssembly module.</span></div>
  </div>
  <footer>Generated by any-to-wasm</footer>
</div>
<script src="wasi-shim.js"></script>
<script src="app.js"></script>
</body>
</html>
`;
}

function wasiJs() {
  return `const outEl = document.getElementById('output');
const statusEl = document.getElementById('status');
const runBtn = document.getElementById('run-btn');

function append(text, cls) {
  const span = document.createElement('span');
  if (cls) span.className = cls;
  span.textContent = text;
  outEl.appendChild(span);
  outEl.scrollTop = outEl.scrollHeight;
}

async function runProgram() {
  runBtn.disabled = true;
  outEl.textContent = '';
  statusEl.textContent = 'running...';
  try {
    const shim = createMinimalWasi({
      onStdout: (t) => append(t),
      onStderr: (t) => append(t, 'err'),
    });
    const resp = await fetch('app.wasm');
    const bytes = await resp.arrayBuffer();
    const { instance } = await WebAssembly.instantiate(bytes, shim.imports);
    shim.setMemory(instance.exports.memory);
    try {
      instance.exports._start();
      statusEl.textContent = 'exited 0';
    } catch (e) {
      if (e && typeof e.__wasiExitCode === 'number') {
        statusEl.textContent = 'exited ' + e.__wasiExitCode;
      } else {
        throw e;
      }
    }
  } catch (err) {
    append(String(err && err.message ? err.message : err), 'err');
    statusEl.textContent = 'error';
  } finally {
    runBtn.disabled = false;
  }
}

runBtn.addEventListener('click', runProgram);
runProgram();
`;
}

function pythonHtml({ title, entryFile }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<link rel="stylesheet" href="style.css" />
</head>
<body>
<div class="wrap">
  <header>
    <span class="badge">Python &rarr; WebAssembly (Pyodide)</span>
    <h1>${escapeHtml(entryFile)}</h1>
    <p>Runs with <a href="https://pyodide.org" target="_blank" rel="noopener">Pyodide</a>, a full CPython interpreter compiled to WebAssembly, directly in your browser.</p>
  </header>
  <div class="panel">
    <button id="run-btn" disabled>Loading Python runtime&hellip;</button>
    <span id="status" class="badge" style="margin-left:.5rem;background:transparent;color:var(--muted)"></span>
  </div>
  <div class="panel">
    <div id="output" class="terminal"><span class="muted">Loading Pyodide (CPython compiled to WebAssembly)&hellip;</span></div>
  </div>
  <footer>Generated by any-to-wasm</footer>
</div>
<script src="https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.js"></script>
<script src="app.js"></script>
</body>
</html>
`;
}

function pythonJs({ entryFile, pyFiles }) {
  return `const outEl = document.getElementById('output');
const statusEl = document.getElementById('status');
const runBtn = document.getElementById('run-btn');
const ENTRY_FILE = ${JSON.stringify(entryFile)};
const PY_FILES = ${JSON.stringify(pyFiles)};

function append(text, cls) {
  const span = document.createElement('span');
  if (cls) span.className = cls;
  span.textContent = text;
  outEl.appendChild(span);
  outEl.scrollTop = outEl.scrollHeight;
}

let pyodideReady = null;

async function loadPyodideOnce() {
  if (pyodideReady) return pyodideReady;
  pyodideReady = (async () => {
    const pyodide = await loadPyodide();
    for (const rel of PY_FILES) {
      const resp = await fetch('pysrc/' + rel);
      const text = await resp.text();
      const dir = rel.split('/').slice(0, -1).join('/');
      if (dir) pyodide.FS.mkdirTree(dir);
      pyodide.FS.writeFile(rel, text);
    }
    return pyodide;
  })();
  return pyodideReady;
}

async function runProgram() {
  runBtn.disabled = true;
  outEl.textContent = '';
  statusEl.textContent = 'loading...';
  try {
    const pyodide = await loadPyodideOnce();
    statusEl.textContent = 'running...';
    pyodide.setStdout({ batched: (t) => append(t + '\\n') });
    pyodide.setStderr({ batched: (t) => append(t + '\\n', 'err') });
    await pyodide.runPythonAsync(
      "import runpy\\nrunpy.run_path(" + JSON.stringify(ENTRY_FILE) + ", run_name='__main__')"
    );
    statusEl.textContent = 'done';
  } catch (err) {
    append(String(err && err.message ? err.message : err), 'err');
    statusEl.textContent = 'error';
  } finally {
    runBtn.disabled = false;
  }
}

runBtn.addEventListener('click', runProgram);
loadPyodideOnce().then(() => {
  runBtn.disabled = false;
  runBtn.textContent = 'Run';
  statusEl.textContent = 'ready';
  runProgram();
});
`;
}

function genericHtml({ title, files, note }) {
  const items = files
    .map(
      (f, i) =>
        `<li><a href="#" data-idx="${i}" class="file-link">${escapeHtml(f)}</a></li>`
    )
    .join('\n');
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<link rel="stylesheet" href="style.css" />
</head>
<body>
<div class="wrap">
  <header>
    <span class="badge">Source viewer</span>
    <h1>${escapeHtml(title)}</h1>
    <p>${escapeHtml(note)}</p>
  </header>
  <div class="grid-2">
    <div class="panel">
      <ul class="file-tree">${items}</ul>
    </div>
    <div class="panel">
      <pre class="code" id="code">Select a file to view its source.</pre>
    </div>
  </div>
  <footer>Generated by any-to-wasm</footer>
</div>
<script src="app.js"></script>
</body>
</html>
`;
}

function genericJs({ files }) {
  return `const FILES = ${JSON.stringify(files)};
const codeEl = document.getElementById('code');
document.querySelectorAll('.file-link').forEach((el) => {
  el.addEventListener('click', async (e) => {
    e.preventDefault();
    document.querySelectorAll('.file-link').forEach((l) => l.classList.remove('active'));
    el.classList.add('active');
    const idx = Number(el.dataset.idx);
    const resp = await fetch('src/' + FILES[idx]);
    codeEl.textContent = await resp.text();
  });
});
`;
}

function renderSite(outputDir, opts) {
  fs.writeFileSync(path.join(outputDir, 'style.css'), SHARED_CSS);
  let html;
  let js;
  if (opts.bodyTemplate === 'wasi') {
    html = wasiHtml(opts);
    js = wasiJs(opts);
  } else if (opts.bodyTemplate === 'python') {
    html = pythonHtml(opts);
    js = pythonJs(opts);
  } else if (opts.bodyTemplate === 'generic') {
    html = genericHtml(opts);
    js = genericJs(opts);
  } else {
    throw new Error(`Unknown template ${opts.bodyTemplate}`);
  }
  fs.writeFileSync(path.join(outputDir, 'index.html'), html);
  fs.writeFileSync(path.join(outputDir, 'app.js'), js);
}

module.exports = { renderSite, escapeHtml };
